name: CI With JavaScript and Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Debug Environment Variables Length
        run: |
          echo "BASE_URL length: ${#BASE_URL}"
          echo "EMAIL length: ${#EMAIL}"
          echo "PASSWORD length: ${#PASSWORD}"

      - name: Run tests and generate Allure results
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Running tests..."
          npm test

      - name: Generate Allure report
        if: always()
        run: npm run allure:generate
      
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'allure-report'

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}